version: "3"

services:
  app:
    build: ./app/
    volumes:
      - ./app:/app
      - ./app/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./app/.envs/.postgres
    depends_on:
      - db
  db:
    image: ankane/pgvector
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./app/.envs/.postgres
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - /dev/null:/etc/nginx/conf.d/default.conf
      - ./app/media:/media
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - app